export interface ProfileModel {
  aero: string
  apple_connected: string
  apple_id: string
  card_cover: string
  chat_sound: string
  email_friend_requests: string
  email_mentions: string
  email_post_comments: string
  email_post_likes: string
  email_post_shares: string
  email_profile_visits: string
  email_wall_posts: string
  exolved: string
  facebook_connected: string
  facebook_id: string
  fifth: string
  first: string
  firstresponder: string
  firstresponder_badge: string
  fourth: string
  game1: string
  game2: string
  game3: string
  gg: string
  gg_badge: string
  google_connected: string
  google_id: string
  instagram_connected: string
  instagram_id: string
  layout: string
  lfg: string
  lfg_text: string
  linkedin_connected: string
  linkedin_id: string
  live: string
  military: string
  military_badge: string
  notifications_sound: string
  onesignal_user_id: string
  partner_member: string
  poss: string
  reason_ban: string
  safe: string
  searching: string
  second: string
  spotify: string
  squad_name: string
  sway: string
  third: string
  titus: string
  total_xp: string
  twitter_connected: string
  twitter_id: string
  user_activated: string
  user_affiliate_balance: string
  user_album_covers: string
  user_album_pictures: string
  user_album_timeline: string
  user_banned: string
  user_biography: string
  user_birthdate: string
  user_boosted_pages: string
  user_boosted_posts: string
  user_chat_enabled: string
  user_country: string
  user_cover: string
  user_cover_id: string
  user_cover_position: string
  user_current_city: string
  user_edu_class: string
  user_edu_major: string
  user_edu_school: string
  user_email: string
  user_email_verified: string
  user_failed_login_count: string
  user_failed_login_ip: string
  user_first_failed_login: string
  user_firstname: string
  user_gender: string
  user_group: string
  user_hometown: string
  user_id: string
  user_language: string
  user_last_seen: string
  user_lastname: string
  user_latitude: string
  user_live_messages_counter: string
  user_live_messages_lastid: string
  user_live_notifications_counter: string
  user_live_notifications_lastid: string
  user_live_requests_counter: string
  user_live_requests_lastid: string
  user_location_updated: string
  user_longitude: string
  user_mod: string
  user_name: string
  user_package: string
  user_phone: string
  user_phone_verified: string
  user_picture: string
  user_picture_id: string
  user_pinned_post: string
  user_points: string
  user_privacy_basic: string
  user_privacy_birthdate: string
  user_privacy_education: string
  user_privacy_events: string
  user_privacy_friends: string
  user_privacy_gender: string
  user_privacy_gifts: string
  user_privacy_groups: string
  user_privacy_location: string
  user_privacy_newsletter: string
  user_privacy_other: string
  user_privacy_pages: string
  user_privacy_photos: string
  user_privacy_poke: string
  user_privacy_relationship: string
  user_privacy_wall: string
  user_privacy_work: string
  user_profile_background: string
  user_rating: string
  user_referrer_id: string
  user_registered: string
  user_relationship: string
  user_reset_key: string
  user_reseted: string
  user_social_activision: string
  user_social_battle: string
  user_social_discord: string
  user_social_epic: string
  user_social_facebook: string
  user_social_gog: string
  user_social_instagram: string
  user_social_linkedin: string
  user_social_origin: string
  user_social_playstation: string
  user_social_steam: string
  user_social_switch: string
  user_social_tiktok: string
  user_social_trovo: string
  user_social_twitch: string
  user_social_twitter: string
  user_social_xbox: string
  user_social_youtube: string
  user_sponsored: string
  user_staff: string
  user_started: string
  user_subscribed: string
  user_subscription_date: string
  user_token: string
  user_two_factor_enabled: string
  user_two_factor_gsecret: string
  user_two_factor_key: string
  user_two_factor_type: string
  user_verified: string
  user_wallet_balance: string
  user_website: string
  user_work_place: string
  user_work_title: string
  user_work_url: string
  valk: string
  vkontakte_connected: string
  vkontakte_id: string
  zodiac: string
}
